name: Release PRs

on:
  push:
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release
          config: release-plz.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-pr:
    name: Create or update release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run release-plz
        uses: release-plz/action@v0.5
        with:
          command: release-pr
          config: release-plz.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
